version: "3.8"
services:
  server:
    container_name: server
    image: "server"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./src:/server/src