name: Load environment variables and build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies and build
        run: |
          cd client
          bun install
          bun build:src
        env:
          VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}
          VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          VITE_SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
