name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v40.1.10

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build
        env:
          VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}
          VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          VITE_SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
